# Generated by Django 3.0.5 on 2020-04-22 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=60, verbose_name='Origen')),
                ('destino', models.CharField(max_length=60, verbose_name='Destino')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('horario', models.TimeField(verbose_name='Horario')),
                ('mapa', models.URLField(max_length=500, verbose_name='Mapa')),
            ],
        ),
    ]
