# Generated by Django 3.0.5 on 2020-04-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaje', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='lugares',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
